version: '3.8'

services:
  spark-master:
    image: bitnami/spark:3.5
    volumes:
      - ../../../.data:/data # Mount host 'data' folder to container '/data'
      - ./spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080' # Spark Master Web UI
      - '7077:7077' # Spark Master Port

  spark-worker:
    image: bitnami/spark:3.5
    volumes:
      - ../../../.data:/data # Mount host 'data' folder to container '/data'
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_MEMORY=8g
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    depends_on:
      - spark-master
    deploy:
      resources:
        limits:
          memory: 8g